server:
  port: 9999

spring:
  application:
    name: CODEBASE
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  type-aliases-package: jhlz.code.web.entity
